### ISSUE TITLE
best practice  for motif analysis from histone modification ChIP-seq 

### ISSUE THREAD

**Issue by crazyhottommy** [simonvh/gimmemotifs#63]
Hi,

I was reading http://gimmemotifs.readthedocs.io/en/master/reference.html#best-practices-and-tips

```
-w or –width

This is the width of the sequences used for motif prediction. Smaller sequences will result in a faster analysis, but you are of course limited by the accuracy of your data. For the tested ChIP-seq data sets 200 performs fine.

Running on FASTA files
It is possible to run GimmeMotifs on a FASTA file as input instead of a BED file. This is detected automatically if your input file is correctly formatted according to FASTA specifications. In this case it is not possible to generate a genomic matched background, so only the random Markov background will be used. **Please note that for best results, all the sequences should be of the same length**. This is not necessary for motif prediction, but the statistics and positional preference plots will be wrong if sequences have different lengths. Also see the next section.
```
The peaks from histone modification ChIP-seq are of different length. some of them are 6kb long (H3K27ac). in this case, how should one specify the -w?

I noticed that if I use the peak length of variable length in `gimme malestrom`, it still gives me results. There is no option for -w for this command. do I need to set it up in the config file?

If the peak length are not of the same length. How the 200bp position is determined?

Thanks,
Tommy

**Comment by simonvh** [comment]
Hi Tommy, 

In general using longer sequences for motif analysis does not yield great results. For *de novo* motif finding, the shorter your sequences are the easier it is to find relevant motifs within the "background" sequence. That's why the default for `gimme motifs` is 200. You can change the `-w` parameter, and then the program will take the center of the input regions and use the region of the specified width centered on that location.

However, in the case of H3K27ac (and really any other histone modification), what I recommend is using another source of information to obtain the relevant regulatory regions, as normally H3K27ac peaks are much too broad for an informative motif analysis. For instance, you can take accessible regions (ATAC-seq, DNaseI) or p300 peaks. You intersect the summit of these peaks with your H3K27ac peaks and use that for motif analysis. The difference in the results you get can be quite significant! You can even use, for example all the ROADMAP DNaseI peaks for the intersection (as I think you're working in human, right?).

**Comment by crazyhottommy** [comment]
yes, I am working with human data. I do realize the problem you are mentioning and thanks for the tips. for `gimme maelstrom`, I have to set -w in the config file right? it is not exposed to the commands line.

**Comment by simonvh** [comment]
gimme maelstrom uses the input as given. Whatever the size of the input
regions is, that will be used.

**Comment by crazyhottommy** [comment]
Thanks for confirming this. closing now.
